import type { SeedSnippet } from "./snippets";

export const commandSnippets: SeedSnippet[] = [
  {
    title: "list-long",
    content: "ls -la",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "list-hidden",
    content: "ls -a",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "pwd",
    content: "pwd",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "cd-home",
    content: "cd ~",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "cd-parent",
    content: "cd ..",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "mkdir-parents",
    content: "mkdir -p logs/archive/2024",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "rm-file",
    content: "rm -f temp.txt",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "cp-recursive",
    content: "cp -r src src.bak",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "mv-rename",
    content: "mv old.txt new.txt",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "touch-file",
    content: "touch README.md",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "cat-file",
    content: "cat package.json",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "head-lines",
    content: "head -n 20 access.log",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "tail-lines",
    content: "tail -n 50 error.log",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "tail-follow",
    content: "tail -f /var/log/nginx/access.log",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "wc-lines",
    content: "wc -l *.ts",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "echo-hello",
    content: 'echo "Hello, World!"',
    category: "command",
    difficulty: "easy",
  },
  {
    title: "env-export",
    content: "export NODE_ENV=production",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "which-node",
    content: "which node",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "node-version",
    content: "node --version",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "pnpm-version",
    content: "pnpm --version",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "chmod-exec",
    content: "chmod +x deploy.sh",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "chown-user",
    content: "chown user:group file.txt",
    category: "command",
    difficulty: "medium",
  },
  {
    title: "du-size",
    content: "du -sh *",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "df-disk",
    content: "df -h",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "free-mem",
    content: "free -h",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "uptime",
    content: "uptime",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "whoami",
    content: "whoami",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "hostname",
    content: "hostname",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "date-iso",
    content: "date -Iseconds",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "clear-screen",
    content: "clear",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "history",
    content: "history | tail -20",
    category: "pipeline",
    difficulty: "easy",
  },
  {
    title: "alias-ll",
    content: 'alias ll="ls -la"',
    category: "command",
    difficulty: "easy",
  },
  {
    title: "source-env",
    content: "source .env",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "printenv-path",
    content: "printenv PATH",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "unset-var",
    content: "unset TEMP_VAR",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "grep-recursive",
    content: 'grep -r "pattern" ./src',
    category: "command",
    difficulty: "easy",
  },
  {
    title: "grep-ignore-case",
    content: "grep -i error app.log",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "grep-count",
    content: 'grep -c "404" access.log',
    category: "command",
    difficulty: "medium",
  },
  {
    title: "grep-invert",
    content: 'grep -v "^#" config.conf',
    category: "command",
    difficulty: "medium",
  },
  {
    title: "find-by-name",
    content: 'find . -name "*.sh" -type f',
    category: "command",
    difficulty: "easy",
  },
  {
    title: "find-by-size",
    content: "find . -type f -size +10M",
    category: "command",
    difficulty: "medium",
  },
  {
    title: "find-mtime",
    content: "find . -mtime -7 -type f",
    category: "command",
    difficulty: "medium",
  },
  {
    title: "find-exec-rm",
    content: 'find . -name "*.tmp" -delete',
    category: "command",
    difficulty: "medium",
  },
  {
    title: "locate-file",
    content: "locate nginx.conf",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "sed-replace",
    content: "sed -i 's/foo/bar/g' config.txt",
    category: "command",
    difficulty: "medium",
  },
  {
    title: "sed-print-range",
    content: "sed -n '10,20p' file.txt",
    category: "command",
    difficulty: "medium",
  },
  {
    title: "awk-print-col",
    content: "awk '{print $1}' access.log",
    category: "command",
    difficulty: "medium",
  },
  {
    title: "awk-sum",
    content: "awk '{sum+=$3} END {print sum}' data.txt",
    category: "pipeline",
    difficulty: "hard",
  },
  {
    title: "cut-fields",
    content: "cut -d: -f1 /etc/passwd",
    category: "command",
    difficulty: "medium",
  },
  {
    title: "sort-numeric",
    content: "sort -n numbers.txt",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "sort-reverse",
    content: "sort -r names.txt",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "uniq-count",
    content: "sort file.txt | uniq -c",
    category: "pipeline",
    difficulty: "medium",
  },
  {
    title: "tr-lower",
    content: "echo \"HELLO\" | tr '[:upper:]' '[:lower:]'",
    category: "pipeline",
    difficulty: "easy",
  },
  {
    title: "xargs-rm",
    content: 'find . -name "*.bak" | xargs rm -f',
    category: "pipeline",
    difficulty: "medium",
  },
  {
    title: "tee-output",
    content: "npm test 2>&1 | tee results.log",
    category: "pipeline",
    difficulty: "medium",
  },
  {
    title: "curl-silent",
    content: "curl -fsSL https://example.com/install.sh",
    category: "command",
    difficulty: "medium",
  },
  {
    title: "curl-headers",
    content: "curl -I https://example.com",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "curl-post",
    content: 'curl -X POST -d "key=val" https://api.example.com',
    category: "command",
    difficulty: "medium",
  },
  {
    title: "wget-quiet",
    content: "wget -qO- https://api.github.com/repos/vercel/next",
    category: "command",
    difficulty: "medium",
  },
  {
    title: "ping-host",
    content: "ping -c 4 google.com",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "nslookup",
    content: "nslookup example.com",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "dig-dns",
    content: "dig example.com",
    category: "command",
    difficulty: "medium",
  },
  {
    title: "netstat-ports",
    content: "netstat -tuln | grep LISTEN",
    category: "pipeline",
    difficulty: "medium",
  },
  {
    title: "ss-ports",
    content: "ss -tuln",
    category: "command",
    difficulty: "medium",
  },
  {
    title: "lsof-port",
    content: "lsof -i :3000",
    category: "command",
    difficulty: "medium",
  },
  {
    title: "kill-port",
    content: "lsof -ti:3000 | xargs kill -9",
    category: "pipeline",
    difficulty: "medium",
  },
  {
    title: "ps-grep",
    content: "ps aux | grep node",
    category: "pipeline",
    difficulty: "easy",
  },
  {
    title: "kill-process",
    content: 'kill -9 $(pgrep -f "next dev")',
    category: "command",
    difficulty: "medium",
  },
  {
    title: "top-once",
    content: "top -l 1 | head -20",
    category: "pipeline",
    difficulty: "medium",
  },
  {
    title: "tar-create",
    content: "tar -czf archive.tar.gz ./dist",
    category: "command",
    difficulty: "medium",
  },
  {
    title: "tar-extract",
    content: "tar -xzf archive.tar.gz -C /tmp",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "zip-dir",
    content: "zip -r backup.zip ./src",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "unzip-file",
    content: "unzip archive.zip -d ./output",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "gzip-file",
    content: "gzip -9 large.log",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "gunzip-file",
    content: "gunzip file.gz",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "rsync-remote",
    content: "rsync -avz ./dist/ user@server:/var/www/",
    category: "command",
    difficulty: "hard",
  },
  {
    title: "scp-file",
    content: "scp file.txt user@host:/tmp/",
    category: "command",
    difficulty: "medium",
  },
  {
    title: "ssh-remote",
    content: 'ssh user@host "uptime"',
    category: "command",
    difficulty: "medium",
  },
  {
    title: "ssh-keygen",
    content: 'ssh-keygen -t ed25519 -C "user@host"',
    category: "command",
    difficulty: "medium",
  },
  {
    title: "git-status",
    content: "git status --short",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "git-log",
    content: "git log --oneline | head -20",
    category: "pipeline",
    difficulty: "easy",
  },
  {
    title: "git-diff",
    content: "git diff --stat",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "git-add-all",
    content: "git add -A",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "git-commit",
    content: 'git commit -m "fix: resolve bug"',
    category: "command",
    difficulty: "easy",
  },
  {
    title: "git-push",
    content: "git push origin main",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "git-pull",
    content: "git pull origin main",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "git-fetch",
    content: "git fetch --all --prune",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "git-branch",
    content: "git checkout -b feature/new-branch",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "git-stash",
    content: 'git stash push -m "wip: feature"',
    category: "command",
    difficulty: "easy",
  },
  {
    title: "git-stash-pop",
    content: "git stash pop",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "git-reset-soft",
    content: "git reset --soft HEAD~1",
    category: "command",
    difficulty: "medium",
  },
  {
    title: "git-rebase",
    content: "git rebase -i HEAD~3",
    category: "command",
    difficulty: "medium",
  },
  {
    title: "git-cherry-pick",
    content: "git cherry-pick abc1234",
    category: "command",
    difficulty: "medium",
  },
  {
    title: "git-tag",
    content: "git tag v1.0.0 && git push origin v1.0.0",
    category: "command",
    difficulty: "medium",
  },
  {
    title: "git-clean",
    content: "git clean -fd",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "git-blame",
    content: "git blame -L 10,20 src/main.ts",
    category: "command",
    difficulty: "medium",
  },
  {
    title: "git-bisect",
    content: "git bisect start && git bisect bad HEAD",
    category: "command",
    difficulty: "hard",
  },
  {
    title: "gh-pr-create",
    content: 'gh pr create --title "Fix bug" --body "Details"',
    category: "command",
    difficulty: "medium",
  },
  {
    title: "gh-pr-list",
    content: "gh pr list --state open",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "gh-issue-list",
    content: "gh issue list",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "docker-ps",
    content: "docker ps -a",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "docker-images",
    content: "docker images",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "docker-build",
    content: "docker build -t myapp:latest .",
    category: "command",
    difficulty: "medium",
  },
  {
    title: "docker-run",
    content: "docker run -d -p 3000:3000 myapp",
    category: "command",
    difficulty: "medium",
  },
  {
    title: "docker-stop",
    content: "docker stop mycontainer",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "docker-rm",
    content: "docker rm -f mycontainer",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "docker-logs",
    content: "docker logs --tail 100 mycontainer",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "docker-exec",
    content: "docker exec -it mycontainer bash",
    category: "command",
    difficulty: "medium",
  },
  {
    title: "docker-prune",
    content: "docker system prune -af",
    category: "command",
    difficulty: "medium",
  },
  {
    title: "docker-compose-up",
    content: "docker compose up -d",
    category: "command",
    difficulty: "medium",
  },
  {
    title: "docker-compose-down",
    content: "docker compose down",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "kubectl-pods",
    content: "kubectl get pods",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "kubectl-logs",
    content: "kubectl logs -f deployment/api",
    category: "command",
    difficulty: "medium",
  },
  {
    title: "kubectl-apply",
    content: "kubectl apply -f deployment.yaml",
    category: "command",
    difficulty: "medium",
  },
  {
    title: "npm-install",
    content: "npm install",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "npm-test",
    content: "npm test",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "npm-build",
    content: "npm run build",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "pnpm-install",
    content: "pnpm install",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "pnpm-dev",
    content: "pnpm dev",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "pnpm-lint",
    content: "pnpm lint",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "npx-drizzle",
    content: "npx drizzle-kit push",
    category: "command",
    difficulty: "medium",
  },
  {
    title: "jq-parse",
    content: "curl -s api.example.com/data | jq '.items[].name'",
    category: "pipeline",
    difficulty: "medium",
  },
  {
    title: "jq-filter",
    content: "cat data.json | jq '.version'",
    category: "pipeline",
    difficulty: "easy",
  },
  {
    title: "pipe-grep-awk",
    content: "cat access.log | grep \"404\" | awk '{print $7}'",
    category: "pipeline",
    difficulty: "medium",
  },
  {
    title: "pipe-ps-sort",
    content: "ps aux | sort -k3 -nr | head -5",
    category: "pipeline",
    difficulty: "medium",
  },
  {
    title: "pipe-wc-lines",
    content: 'find . -name "*.ts" | xargs wc -l | sort -n',
    category: "pipeline",
    difficulty: "medium",
  },
  {
    title: "pipe-df-grep",
    content: "df -h | grep -v tmpfs",
    category: "pipeline",
    difficulty: "easy",
  },
  {
    title: "pipe-git-diff",
    content: "git diff --stat HEAD~1 | tail -1",
    category: "pipeline",
    difficulty: "medium",
  },
  {
    title: "pipe-curl-jq",
    content: "curl -s https://api.github.com/users/octocat | jq '.login'",
    category: "pipeline",
    difficulty: "medium",
  },
  {
    title: "pipe-zgrep",
    content: 'zgrep -h "error" /var/log/*.gz | tail -50',
    category: "pipeline",
    difficulty: "hard",
  },
  {
    title: "pipe-ls-grep",
    content: 'ls -la | grep "^d"',
    category: "pipeline",
    difficulty: "easy",
  },
  {
    title: "pipe-history-grep",
    content: "history | grep git | tail -10",
    category: "pipeline",
    difficulty: "easy",
  },
  {
    title: "openssl-s_client",
    content: "echo | openssl s_client -connect example.com:443 2>/dev/null | head -5",
    category: "pipeline",
    difficulty: "hard",
  },
  {
    title: "nc-port-check",
    content: "nc -zv localhost 5432",
    category: "command",
    difficulty: "medium",
  },
  {
    title: "http-server",
    content: "python3 -m http.server 8080",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "diff-files",
    content: "diff file1.txt file2.txt",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "diff-process-sub",
    content: "diff <(sort a.txt) <(sort b.txt)",
    category: "command",
    difficulty: "hard",
  },
  {
    title: "watch-command",
    content: 'watch -n 2 "df -h /"',
    category: "command",
    difficulty: "medium",
  },
  {
    title: "crontab-list",
    content: "crontab -l",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "systemctl-status",
    content: "systemctl status nginx",
    category: "command",
    difficulty: "medium",
  },
  {
    title: "journalctl-tail",
    content: "journalctl -u nginx -n 50",
    category: "command",
    difficulty: "medium",
  },
  {
    title: "rg-pattern",
    content: 'rg "TODO" src/',
    category: "command",
    difficulty: "easy",
  },
  {
    title: "rg-files",
    content: 'rg -l "error" logs/',
    category: "command",
    difficulty: "easy",
  },
  {
    title: "rg-count",
    content: 'rg -c "import" *.ts',
    category: "command",
    difficulty: "medium",
  },
  {
    title: "rg-type",
    content: 'rg -t py "def main"',
    category: "command",
    difficulty: "medium",
  },
  {
    title: "fd-name",
    content: "fd -e ts",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "fd-hidden",
    content: "fd -H config",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "bat-file",
    content: "bat README.md",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "exa-long",
    content: "exa -la",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "tree-depth",
    content: "tree -L 2",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "realpath",
    content: "realpath ./link",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "readlink",
    content: "readlink -f bin/script",
    category: "command",
    difficulty: "medium",
  },
  {
    title: "stat-file",
    content: "stat package.json",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "file-type",
    content: "file deploy.sh",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "basename",
    content: "basename /var/log/app.log",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "dirname",
    content: "dirname /var/log/app.log",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "ln-symbolic",
    content: "ln -s /opt/app current",
    category: "command",
    difficulty: "medium",
  },
  {
    title: "ln-hard",
    content: "ln target hardlink",
    category: "command",
    difficulty: "medium",
  },
  {
    title: "install-perms",
    content: "install -m 755 script.sh /usr/local/bin/",
    category: "command",
    difficulty: "hard",
  },
  {
    title: "mktemp-dir",
    content: "mktemp -d",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "shred-file",
    content: "shred -u secret.txt",
    category: "command",
    difficulty: "hard",
  },
  {
    title: "split-lines",
    content: "split -l 1000 big.log",
    category: "command",
    difficulty: "medium",
  },
  {
    title: "paste-merge",
    content: "paste names.txt scores.txt",
    category: "command",
    difficulty: "medium",
  },
  {
    title: "join-tables",
    content: "join -t, users.csv orders.csv",
    category: "command",
    difficulty: "hard",
  },
  {
    title: "comm-files",
    content: "comm -12 sorted1 sorted2",
    category: "command",
    difficulty: "hard",
  },
  {
    title: "expand-tabs",
    content: "expand -t 4 indented.txt",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "unexpand-tabs",
    content: "unexpand -t 4 spaces.txt",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "fmt-wrap",
    content: "fmt -w 80 draft.md",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "fold-width",
    content: "fold -w 120 wide.txt",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "nl-number",
    content: "nl -ba script.sh",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "pr-pages",
    content: "pr -l 66 -w 80 report.txt",
    category: "command",
    difficulty: "hard",
  },
  {
    title: "tac-reverse",
    content: "tac numbered.txt",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "rev-chars",
    content: 'rev <<< "hello"',
    category: "command",
    difficulty: "easy",
  },
  {
    title: "shuf-random",
    content: "shuf -n 5 list.txt",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "shuf-lines",
    content: "shuf lines.txt",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "seq-range",
    content: "seq 1 10",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "yes-stream",
    content: "yes | head -n 5",
    category: "pipeline",
    difficulty: "easy",
  },
  {
    title: "printf-format",
    content: 'printf "%s\\n" foo bar',
    category: "command",
    difficulty: "easy",
  },
  {
    title: "bc-calc",
    content: 'echo "2+2" | bc',
    category: "pipeline",
    difficulty: "easy",
  },
  {
    title: "expr-math",
    content: "expr 10 + 5",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "factor-num",
    content: "factor 12345",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "base64-encode",
    content: "echo -n test | base64",
    category: "pipeline",
    difficulty: "easy",
  },
  {
    title: "base64-decode",
    content: "echo dGVzdA== | base64 -d",
    category: "pipeline",
    difficulty: "medium",
  },
  {
    title: "md5sum-file",
    content: "md5sum package-lock.json",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "sha256sum",
    content: "sha256sum release.tar.gz",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "shasum-verify",
    content: "shasum -a 256 -c checksums.txt",
    category: "command",
    difficulty: "medium",
  },
  {
    title: "gpg-sign",
    content: "gpg --sign message.txt",
    category: "command",
    difficulty: "hard",
  },
  {
    title: "gpg-verify",
    content: "gpg --verify release.sig",
    category: "command",
    difficulty: "hard",
  },
  {
    title: "ssh-copy-id",
    content: "ssh-copy-id user@host",
    category: "command",
    difficulty: "medium",
  },
  {
    title: "ssh-tunnel",
    content: "ssh -L 5432:localhost:5432 user@bastion",
    category: "command",
    difficulty: "hard",
  },
  {
    title: "ssh-agent-add",
    content: "ssh-add ~/.ssh/id_ed25519",
    category: "command",
    difficulty: "medium",
  },
  {
    title: "scp-recursive",
    content: "scp -r ./assets user@host:/var/www/",
    category: "command",
    difficulty: "medium",
  },
  {
    title: "rsync-delete",
    content: "rsync -av --delete src/ dst/",
    category: "command",
    difficulty: "medium",
  },
  {
    title: "rsync-dry",
    content: "rsync -avn src/ dst/",
    category: "command",
    difficulty: "medium",
  },
  {
    title: "curl-json",
    content: "curl -s https://api.example.com/v1/status",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "curl-put",
    content: 'curl -X PUT -H "Content-Type: application/json" -d "{}" api/item',
    category: "command",
    difficulty: "hard",
  },
  {
    title: "curl-delete",
    content: "curl -X DELETE https://api.example.com/item/1",
    category: "command",
    difficulty: "medium",
  },
  {
    title: "curl-auth",
    content: "curl -u user:pass https://api.example.com/me",
    category: "command",
    difficulty: "medium",
  },
  {
    title: "curl-timeout",
    content: "curl --max-time 5 https://slow.example.com",
    category: "command",
    difficulty: "medium",
  },
  {
    title: "curl-retry",
    content: "curl --retry 3 https://api.example.com",
    category: "command",
    difficulty: "medium",
  },
  {
    title: "wget-mirror",
    content: "wget -mk https://example.com",
    category: "command",
    difficulty: "hard",
  },
  {
    title: "httpie-get",
    content: "http GET api.example.com/users",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "httpie-post",
    content: "http POST api.example.com/users name=alice",
    category: "command",
    difficulty: "medium",
  },
  {
    title: "dig-short",
    content: "dig +short example.com",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "dig-mx",
    content: "dig MX example.com",
    category: "command",
    difficulty: "medium",
  },
  {
    title: "host-lookup",
    content: "host example.com",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "whois-domain",
    content: "whois example.com",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "traceroute",
    content: "traceroute example.com",
    category: "command",
    difficulty: "medium",
  },
  {
    title: "mtr-host",
    content: "mtr -r -c 5 example.com",
    category: "command",
    difficulty: "hard",
  },
  {
    title: "ip-addr",
    content: "ip addr show",
    category: "command",
    difficulty: "medium",
  },
  {
    title: "ip-route",
    content: "ip route list",
    category: "command",
    difficulty: "medium",
  },
  {
    title: "ifconfig",
    content: "ifconfig en0",
    category: "command",
    difficulty: "medium",
  },
  {
    title: "route-n",
    content: "route -n get default",
    category: "command",
    difficulty: "medium",
  },
  {
    title: "arp-table",
    content: "arp -a",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "tcpdump-port",
    content: "sudo tcpdump -i any port 443",
    category: "command",
    difficulty: "hard",
  },
  {
    title: "nmap-scan",
    content: "nmap -p 80,443 localhost",
    category: "command",
    difficulty: "hard",
  },
  {
    title: "iptables-list",
    content: "sudo iptables -L -n",
    category: "command",
    difficulty: "hard",
  },
  {
    title: "ufw-status",
    content: "sudo ufw status",
    category: "command",
    difficulty: "medium",
  },
  {
    title: "systemctl-start",
    content: "sudo systemctl start nginx",
    category: "command",
    difficulty: "medium",
  },
  {
    title: "systemctl-stop",
    content: "sudo systemctl stop nginx",
    category: "command",
    difficulty: "medium",
  },
  {
    title: "systemctl-restart",
    content: "sudo systemctl restart nginx",
    category: "command",
    difficulty: "medium",
  },
  {
    title: "systemctl-enable",
    content: "sudo systemctl enable docker",
    category: "command",
    difficulty: "medium",
  },
  {
    title: "journalctl-follow",
    content: "journalctl -f -u app.service",
    category: "command",
    difficulty: "medium",
  },
  {
    title: "dmesg-tail",
    content: "dmesg | tail -20",
    category: "pipeline",
    difficulty: "easy",
  },
  {
    title: "sysctl-read",
    content: "sysctl kern.maxfiles",
    category: "command",
    difficulty: "medium",
  },
  {
    title: "launchctl-list",
    content: "launchctl list | grep com.apple",
    category: "pipeline",
    difficulty: "medium",
  },
  {
    title: "pmset-sleep",
    content: "pmset displaysleepnow",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "caffeinate",
    content: "caffeinate -dims",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "git-clone",
    content: "git clone https://github.com/org/repo.git",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "git-remote-v",
    content: "git remote -v",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "git-show",
    content: "git show HEAD",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "git-shortlog",
    content: "git shortlog -sn",
    category: "command",
    difficulty: "medium",
  },
  {
    title: "git-reflog",
    content: "git reflog --oneline | head",
    category: "pipeline",
    difficulty: "medium",
  },
  {
    title: "git-merge",
    content: "git merge feature/auth",
    category: "command",
    difficulty: "medium",
  },
  {
    title: "git-revert",
    content: "git revert HEAD",
    category: "command",
    difficulty: "medium",
  },
  {
    title: "git-amend",
    content: "git commit --amend --no-edit",
    category: "command",
    difficulty: "medium",
  },
  {
    title: "git-push-force",
    content: "git push --force-with-lease",
    category: "command",
    difficulty: "hard",
  },
  {
    title: "git-fetch-prune",
    content: "git fetch --prune --tags",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "git-worktree-add",
    content: "git worktree add ../hotfix hotfix",
    category: "command",
    difficulty: "hard",
  },
  {
    title: "git-submodule",
    content: "git submodule update --init --recursive",
    category: "command",
    difficulty: "hard",
  },
  {
    title: "gh-repo-clone",
    content: "gh repo clone org/repo",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "gh-release-list",
    content: "gh release list",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "gh-run-list",
    content: "gh run list --limit 5",
    category: "command",
    difficulty: "medium",
  },
  {
    title: "npm-ci",
    content: "npm ci",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "npm-outdated",
    content: "npm outdated",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "npm-audit",
    content: "npm audit --production",
    category: "command",
    difficulty: "medium",
  },
  {
    title: "npm-cache-clean",
    content: "npm cache clean --force",
    category: "command",
    difficulty: "medium",
  },
  {
    title: "pnpm-store-prune",
    content: "pnpm store prune",
    category: "command",
    difficulty: "medium",
  },
  {
    title: "pnpm-why",
    content: "pnpm why react",
    category: "command",
    difficulty: "medium",
  },
  {
    title: "yarn-why",
    content: "yarn why lodash",
    category: "command",
    difficulty: "medium",
  },
  {
    title: "npx-tsc",
    content: "npx tsc --noEmit",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "npx-eslint",
    content: "npx eslint . --max-warnings 0",
    category: "command",
    difficulty: "medium",
  },
  {
    title: "npx-prettier",
    content: "npx prettier --check .",
    category: "command",
    difficulty: "medium",
  },
  {
    title: "node-eval",
    content: 'node -e "console.log(process.version)"',
    category: "command",
    difficulty: "easy",
  },
  {
    title: "python-pip-list",
    content: "python3 -m pip list",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "python-venv",
    content: "python3 -m venv .venv",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "pip-install",
    content: "python3 -m pip install -r requirements.txt",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "pip-freeze",
    content: "python3 -m pip freeze > requirements.txt",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "cargo-build",
    content: "cargo build --release",
    category: "command",
    difficulty: "medium",
  },
  {
    title: "cargo-test",
    content: "cargo test",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "cargo-check",
    content: "cargo check",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "go-build",
    content: "go build ./...",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "go-test",
    content: "go test ./...",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "go-mod-tidy",
    content: "go mod tidy",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "go-vet",
    content: "go vet ./...",
    category: "command",
    difficulty: "medium",
  },
  {
    title: "make-clean",
    content: "make clean",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "make-test",
    content: "make test",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "cmake-configure",
    content: "cmake -B build -S .",
    category: "command",
    difficulty: "medium",
  },
  {
    title: "ninja-build",
    content: "ninja -C build",
    category: "command",
    difficulty: "medium",
  },
  {
    title: "docker-pull",
    content: "docker pull nginx:alpine",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "docker-tag",
    content: "docker tag myapp:latest myapp:v1",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "docker-push",
    content: "docker push myapp:v1",
    category: "command",
    difficulty: "medium",
  },
  {
    title: "docker-inspect",
    content: "docker inspect mycontainer",
    category: "command",
    difficulty: "medium",
  },
  {
    title: "docker-cp",
    content: "docker cp mycontainer:/app/log ./log",
    category: "command",
    difficulty: "medium",
  },
  {
    title: "docker-network-ls",
    content: "docker network ls",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "docker-volume-ls",
    content: "docker volume ls",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "docker-compose-logs",
    content: "docker compose logs -f api",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "docker-compose-build",
    content: "docker compose build --no-cache",
    category: "command",
    difficulty: "medium",
  },
  {
    title: "kubectl-get-nodes",
    content: "kubectl get nodes",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "kubectl-describe",
    content: "kubectl describe pod api-7d8f9",
    category: "command",
    difficulty: "medium",
  },
  {
    title: "kubectl-exec",
    content: "kubectl exec -it api-7d8f9 -- sh",
    category: "command",
    difficulty: "hard",
  },
  {
    title: "kubectl-port-forward",
    content: "kubectl port-forward svc/api 8080:80",
    category: "command",
    difficulty: "hard",
  },
  {
    title: "helm-list",
    content: "helm list -A",
    category: "command",
    difficulty: "medium",
  },
  {
    title: "helm-upgrade",
    content: "helm upgrade --install app ./chart",
    category: "command",
    difficulty: "hard",
  },
  {
    title: "terraform-init",
    content: "terraform init",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "terraform-plan",
    content: "terraform plan -out=plan.tfplan",
    category: "command",
    difficulty: "medium",
  },
  {
    title: "terraform-apply",
    content: "terraform apply plan.tfplan",
    category: "command",
    difficulty: "hard",
  },
  {
    title: "aws-s3-ls",
    content: "aws s3 ls s3://my-bucket/",
    category: "command",
    difficulty: "medium",
  },
  {
    title: "aws-ec2-describe",
    content: "aws ec2 describe-instances --output table",
    category: "command",
    difficulty: "hard",
  },
  {
    title: "gcloud-config-list",
    content: "gcloud config list",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "az-account-show",
    content: "az account show",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "vercel-deploy",
    content: "vercel deploy --prod",
    category: "command",
    difficulty: "medium",
  },
  {
    title: "vercel-env-ls",
    content: "vercel env ls",
    category: "command",
    difficulty: "medium",
  },
  {
    title: "fly-status",
    content: "fly status",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "fly-logs",
    content: "fly logs",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "redis-cli-ping",
    content: "redis-cli ping",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "redis-cli-keys",
    content: 'redis-cli keys "session:*"',
    category: "command",
    difficulty: "medium",
  },
  {
    title: "psql-list-db",
    content: "psql -l",
    category: "command",
    difficulty: "medium",
  },
  {
    title: "psql-connect",
    content: 'psql "$DATABASE_URL"',
    category: "command",
    difficulty: "medium",
  },
  {
    title: "pg-dump",
    content: "pg_dump -Fc mydb > backup.dump",
    category: "command",
    difficulty: "hard",
  },
  {
    title: "mysql-show",
    content: 'mysql -e "SHOW DATABASES;"',
    category: "command",
    difficulty: "medium",
  },
  {
    title: "sqlite3-query",
    content: 'sqlite3 app.db "SELECT COUNT(*) FROM users;"',
    category: "command",
    difficulty: "medium",
  },
  {
    title: "mongosh-status",
    content: 'mongosh --eval "db.serverStatus().ok"',
    category: "command",
    difficulty: "hard",
  },
  {
    title: "eslint-fix",
    content: "npx eslint . --fix",
    category: "command",
    difficulty: "medium",
  },
  {
    title: "oxlint-check",
    content: "npx oxlint",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "vitest-run",
    content: "npx vitest run",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "jest-coverage",
    content: "npx jest --coverage",
    category: "command",
    difficulty: "medium",
  },
  {
    title: "playwright-test",
    content: "npx playwright test",
    category: "command",
    difficulty: "medium",
  },
  {
    title: "turbo-build",
    content: "npx turbo run build",
    category: "command",
    difficulty: "medium",
  },
  {
    title: "next-build",
    content: "npx next build",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "next-start",
    content: "npx next start -p 3000",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "drizzle-studio",
    content: "npx drizzle-kit studio",
    category: "command",
    difficulty: "medium",
  },
  {
    title: "drizzle-generate",
    content: "npx drizzle-kit generate",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "prisma-migrate",
    content: "npx prisma migrate dev",
    category: "command",
    difficulty: "medium",
  },
  {
    title: "prisma-studio",
    content: "npx prisma studio",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "supabase-start",
    content: "npx supabase start",
    category: "command",
    difficulty: "medium",
  },
  {
    title: "stripe-listen",
    content: "stripe listen --forward-to localhost:3000/webhook",
    category: "command",
    difficulty: "hard",
  },
  {
    title: "openssl-genrsa",
    content: "openssl genrsa -out key.pem 2048",
    category: "command",
    difficulty: "hard",
  },
  {
    title: "openssl-req",
    content: "openssl req -new -key key.pem -out csr.pem",
    category: "command",
    difficulty: "hard",
  },
  {
    title: "htop-once",
    content: "htop -n 1",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "iotop",
    content: "sudo iotop -obt",
    category: "command",
    difficulty: "hard",
  },
  {
    title: "vmstat",
    content: "vmstat 1 5",
    category: "command",
    difficulty: "medium",
  },
  {
    title: "iostat",
    content: "iostat -xz 1",
    category: "command",
    difficulty: "medium",
  },
  {
    title: "sar-cpu",
    content: "sar -u 1 3",
    category: "command",
    difficulty: "hard",
  },
  {
    title: "lscpu",
    content: "lscpu",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "lsblk",
    content: "lsblk",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "blkid",
    content: "sudo blkid",
    category: "command",
    difficulty: "medium",
  },
  {
    title: "mount-show",
    content: "mount | column -t",
    category: "pipeline",
    difficulty: "easy",
  },
  {
    title: "findmnt",
    content: "findmnt /",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "fuser-port",
    content: "fuser -n tcp 3000",
    category: "command",
    difficulty: "medium",
  },
  {
    title: "pgrep-name",
    content: "pgrep -fl nginx",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "pkill-name",
    content: 'pkill -f "node server.js"',
    category: "command",
    difficulty: "medium",
  },
  {
    title: "nohup-run",
    content: "nohup ./worker.sh > worker.log 2>&1 &",
    category: "command",
    difficulty: "hard",
  },
  {
    title: "disown-job",
    content: "disown -h %1",
    category: "command",
    difficulty: "hard",
  },
  {
    title: "jobs-list",
    content: "jobs -l",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "fg-job",
    content: "fg %1",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "bg-job",
    content: "bg %1",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "screen-ls",
    content: "screen -ls",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "tmux-new",
    content: "tmux new -s dev",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "tmux-attach",
    content: "tmux attach -t dev",
    category: "command",
    difficulty: "easy",
  },
  {
    title: "crontab-edit",
    content: "crontab -e",
    category: "command",
    difficulty: "medium",
  },
];
